#!/bin/sh

#Host pkg-config script to run on x86, targeting armv7a
#Tested on pkg-config 0.23 (from arm-arago)

export UBUNTU_CORE_ROOTFS=/home/prabindh/work1/ubuntu-core/media/rootfs
#unset this first then set libdir correctly
export PKG_CONFIG_DIR=
export PKG_CONFIG_LIBDIR=${UBUNTU_CORE_ROOTFS}/usr/lib/arm-linux-gnueabi/pkgconfig:${UBUNTU_CORE_ROOTFS}/usr/share/pkgconfig
export PKG_CONFIG_SYSROOT_DIR=${UBUNTU_CORE_ROOTFS}
/opt/toolchain-4.5.3-dynamic/arago-2011.09/armv7a/bin/pkg-config --define-variable=prefix=/home/prabindh/work1/ubuntu-core/media/rootfs "$@"
